version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      backend-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "react*"
          - "expo*"
          - "@types/react*"
    open-pull-requests-limit: 5
    labels:
      - "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "ci"
