import type { FastifyError, FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { captureError } from '../observability/sentry.js';
import { pathOnly } from './logger.js';

/**
 * The last thing between a thrown error and the client (PRD R-31.6).
 *
 * Two things used to leak here, and they are separate problems:
 *
 *   1. The log line passed `{ message: error.message }` explicitly, which
 *      walked straight past the `err` serializer in plugins/logger.ts that
 *      exists precisely to keep vendor prose out of the stream. Passing the
 *      error itself lets that serializer do its job.
 *
 *   2. The RESPONSE returns `error.message` verbatim for anything under 500.
 *      That was safe only by accident: `PlaidApiError` carries `status`, not
 *      `statusCode`, so Fastify defaulted it to 500 and the caller got the
 *      literal string "Internal Server Error". Rename that field, or throw any
 *      other vendor error carrying a 4xx `statusCode`, and vendor text reaches
 *      the client.
 *
 * Fastify's own validation errors are the reason a 4xx message is worth
 * keeping at all: "body must have required property 'goal_id'" is useful, and
 * it is generated by Fastify from our schema, not by a vendor or a user. So
 * the rule is not "never return a message", it is "only return one we wrote".
 */

/** Errors Fastify generates itself, whose messages are derived from our own
 *  route schemas and contain nothing but our field names. `FST_ERR_VALIDATION`
 *  is the one that matters; the rest are shape errors from the same family. */
const SAFE_MESSAGE_CODES = new Set([
  'FST_ERR_VALIDATION',
  'FST_ERR_CTP_EMPTY_JSON_BODY',
  'FST_ERR_CTP_INVALID_MEDIA_TYPE',
  'FST_ERR_CTP_BODY_TOO_LARGE',
  'FST_ERR_NOT_FOUND',
]);

export function registerErrorHandler(app: FastifyInstance): void {
  app.setErrorHandler((error: FastifyError, req: FastifyRequest, reply: FastifyReply) => {
    const status = error.statusCode ?? 500;

    // Pass the error itself, not a hand-picked `message`. The `err` serializer
    // strips the message and keeps the type, the programmatic code and the
    // stack.
    app.log.error({ err: error }, 'request error');

    if (status >= 500) {
      // 5xx ONLY. A 4xx is the client getting it wrong, and reporting those
      // would spend the plan's monthly error budget on validation failures,
      // which is how error tracking ends up switched off for being noisy.
      //
      // Route and method, never the user. Sentry answers "what broke and
      // where"; the correlated Fly log line, which carries `user_id`, answers
      // "for whom". `pathOnly` for the same reason the request serializer uses
      // it: OAuth codes arrive as query parameters.
      captureError(error, { route: pathOnly(req.url), method: req.method, status });
      return reply.status(status).send({ error: 'Internal Server Error' });
    }

    // A 4xx body is client-facing copy. It gets a message only when we wrote
    // it; everything else gets the status text, and the programmatic code so a
    // client can still branch on it.
    if (error.code && SAFE_MESSAGE_CODES.has(error.code)) {
      return reply.status(status).send({ error: error.message, code: error.code });
    }

    return reply.status(status).send({ error: 'Request failed', ...(error.code ? { code: error.code } : {}) });
  });
}
